export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAILURE = "GET_MOVIES_FAILURE";
export const GET_MOVIES_UPDATE = "GET_MOVIES_UPDATE";
export const GET_MOVIES_SEARCH = "GET_MOVIES_SEARCH";
export const GET_MOVIES_BEST = "GET_MOVIES_BEST";
export const GET_MOVIES_SINGLE = "GET_MOVIES_SINGLE";

export const GET_SERIES_REQUEST = "GET_SERIES_REQUEST";
export const GET_SERIES_SUCCESS = "GET_SERIES_SUCCESS";
export const GET_SERIES_FAILURE = "GET_SERIES_FAILURE";
export const GET_SERIES_UPDATE = "GET_SERIES_UPDATE";
export const GET_SERIES_SEARCH = "GET_SERIES_SEARCH";
export const GET_SERIES_BEST = "GET_SERIES_BEST";
export const GET_SERIES_SINGLE = "GET_SERIES_SINGLE";

export const GET_ACTORS_REQUEST = "GET_ACTORS_REQUEST";
export const GET_ACTORS_SUCCESS = "GET_ACTORS_SUCCESS";
export const GET_ACTORS_FAILURE = "GET_ACTORS_FAILURE";
export const GET_ACTORS_UPDATE = "GET_ACTORS_UPDATE";
export const GET_ACTORS_SEARCH = "GET_ACTORS_SEARCH";
export const GET_ACTORS_BEST = "GET_ACTORS_BEST";
export const GET_ACTORS_SINGLE = "GET_ACTORS_SINGLE";
